apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - secret.yaml
  - deployment.yaml
  - httproute.yaml
  - accesscontrolpolicy.yaml
  - identitypropagation.yaml
  - jwks-entra.yaml
  - jwt.yaml
  - tokenexchange.yaml
